name: Build

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
jobs:
  build:
    strategy:
        matrix:
          options:
            - os : ubuntu-latest
              framework: netcoreapp2.1
              is32Bit: False
            # we canb skip windows with netcoreapp as it is coverd by the codecov check
            # - os : windows-latest
            #   framework: netcoreapp2.1
            #   is32Bit: False
            - os : windows-latest
              framework: net472
              is32Bit: False
            - os : windows-latest
              framework: net472
              is32Bit: True

    runs-on:  ${{ matrix.options.os }}

    steps:      
    - uses: actions/checkout@v1
    
    - name: Enable long file paths
      run: git config --global core.longpaths true
      
    - name: Update submodules
      run: git submodule -q update --init
      
    - name: Build
      if : matrix.options.generateCodeCoverage != true
      shell: pwsh
      run: ./build.ps1 "${{matrix.options.framework}}"

    - name: Test
      if : matrix.options.generateCodeCoverage != true
      shell: pwsh
      run: ./run-tests.ps1 "${{matrix.options.framework}}" "${{matrix.options.is32Bit}}" true
      env:
        CI : True