name: Build

on: [pull_request]
    
jobs:
  build:
    strategy:
        matrix:
          options:
            - os : ubuntu-latest
              framework: netcoreapp2.1
              is32Bit: False
            - os : windows-latest
              framework: netcoreapp2.1
              is32Bit: False
            - os : windows-latest
              framework: net472
              is32Bit: False
            - os : windows-latest
              framework: net472
              is32Bit: True

    runs-on:  ${{ matrix.options.os }}

    steps:
    - name: Enable long file paths
      run: git config --system core.longpaths true
      
    - uses: actions/checkout@v1
    
    - name: Update submodules
      run: git submodule -q update --init
      
    - name: Build
      shell: pwsh
      run: ./build.ps1

    - name: Test
      shell: pwsh
      run: ./run-tests.ps1 "${{matrix.options.framework}}" "${{matrix.options.is32Bit}}"
      env:
        CI : True
